/// ktalk — Native Rust CLI for kernel-talk
///
/// This binary provides the same command vocabulary as the Python `ktalk` CLI
/// but delegates to the Python backend via subprocess.  The key benefits are:
///
/// 1. Sub-millisecond startup (vs. ~1.5 s Python import overhead)
/// 2. Shell completions generated by clap
/// 3. A single static binary users can install without Python on PATH
/// 4. Foundation for future native hot-path implementations
///
/// Architecture:
///   ktalk (Rust) → subprocess → python -m cli.ktalk <args>
///
/// Hot paths implemented natively (no Python subprocess):
///   - `ktalk version`  — instant version display
///   - `ktalk env`      — reads ~/.kernel-talk/env.yaml natively
///   - `ktalk status`   — checks store directory + process status
use std::{
    env, fs,
    path::{Path, PathBuf},
    process::{Command, ExitCode},
};

use clap::{Parser, Subcommand};
use colored::Colorize;

// ── Version ───────────────────────────────────────────────────────────────────

const VERSION: &str = env!("CARGO_PKG_VERSION");
const PYTHON_MODULE: &str = "cli.ktalk";

// ── CLI definition ────────────────────────────────────────────────────────────

#[derive(Parser)]
#[command(
    name = "ktalk",
    about = "kernel-talk: Graph-RAG Digital Twin for the Linux kernel",
    version = VERSION,
    long_about = None,
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
    /// Path to Python interpreter (default: searches venv then PATH)
    #[arg(long, env = "KTALK_PYTHON", global = true)]
    python: Option<String>,
    /// Kernel-talk storage directory
    #[arg(long, env = "KTALK_STORAGE", global = true)]
    storage: Option<String>,
}

#[derive(Subcommand)]
enum Commands {
    /// Display version and environment info (native, no Python needed)
    Version,
    /// Show hardware and store status (native, no Python needed)
    Status,
    /// Show detected hardware configuration from env.yaml (native)
    Env,
    /// Generate shell completions
    Completions {
        #[arg(value_enum)]
        shell: clap_complete::Shell,
    },
    /// Search the Mirror index for kernel code
    Query {
        /// Natural language query
        query: Vec<String>,
        /// Number of results
        #[arg(short = 'k', long, default_value = "5")]
        top_k: u32,
        /// Output format: table | json | markdown
        #[arg(long, default_value = "table")]
        format: String,
    },
    /// Build or update the Mirror index
    Index {
        #[arg(long, env = "KTALK_KERNEL_ROOT")]
        kernel: Option<String>,
        #[arg(long, default_value = "500")]
        batch: u32,
    },
    /// Kernel modification subcommands (propose/review/apply etc.)
    Mod {
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
    /// Training pipeline subcommands
    Train {
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
    /// Evaluation harness
    Eval {
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    },
    /// Hardware detection and setup
    Setup {
        #[arg(long)]
        yes: bool,
        #[arg(long)]
        force: bool,
    },
}

// ── Python resolution ─────────────────────────────────────────────────────────

fn find_python(override_: Option<&str>) -> PathBuf {
    if let Some(p) = override_ {
        return PathBuf::from(p);
    }
    // 1. .venv next to the binary's project root
    let exe = env::current_exe().unwrap_or_default();
    let mut root = exe.parent().unwrap_or(Path::new(".")).to_path_buf();
    // Walk up until we find .venv or pyproject.toml
    for _ in 0..6 {
        let venv_python = root.join(".venv/bin/python");
        if venv_python.exists() {
            return venv_python;
        }
        if root.join("pyproject.toml").exists() || root.join("requirements.txt").exists() {
            break;
        }
        root = match root.parent() {
            Some(p) => p.to_path_buf(),
            None => break,
        };
    }
    // 2. $VIRTUAL_ENV
    if let Ok(venv) = env::var("VIRTUAL_ENV") {
        let p = PathBuf::from(venv).join("bin/python");
        if p.exists() { return p; }
    }
    // 3. python3 on PATH
    PathBuf::from("python3")
}

fn project_root() -> PathBuf {
    // Same walk-up as find_python
    let exe = env::current_exe().unwrap_or_default();
    let mut root = exe.parent().unwrap_or(Path::new(".")).to_path_buf();
    for _ in 0..8 {
        if root.join("pyproject.toml").exists()
            || root.join("requirements.txt").exists()
            || root.join("cli").join("ktalk.py").exists()
        {
            return root;
        }
        root = match root.parent() {
            Some(p) => p.to_path_buf(),
            None => break,
        };
    }
    env::current_dir().unwrap_or_default()
}

// ── Subprocess delegation ─────────────────────────────────────────────────────

fn run_python(python: &Path, extra_args: &[&str]) -> ExitCode {
    let proj = project_root();
    let status = Command::new(python)
        .arg("-m")
        .arg(PYTHON_MODULE)
        .args(extra_args)
        .current_dir(&proj)
        .status();
    match status {
        Ok(s) => {
            if s.success() { ExitCode::SUCCESS }
            else { ExitCode::from(s.code().unwrap_or(1) as u8) }
        }
        Err(e) => {
            eprintln!("{} {}", "error:".red().bold(), e);
            ExitCode::FAILURE
        }
    }
}

// ── Native implementations ────────────────────────────────────────────────────

fn cmd_version() -> ExitCode {
    println!(
        "{} {} (Rust CLI frontend)",
        "kernel-talk".cyan().bold(),
        VERSION.yellow()
    );
    println!("  project:  https://github.com/lostadi/kernel-talk");
    println!("  license:  GPL-2.0-only");
    ExitCode::SUCCESS
}

fn ktalk_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_default()
        .join(".kernel-talk")
}

fn cmd_status() -> ExitCode {
    let dir = ktalk_dir();
    println!("{}", "kernel-talk status".cyan().bold());

    // Store
    let store = dir.join("store/chroma");
    if store.exists() {
        println!("  store:    {} {}", "✓".green(), store.display());
    } else {
        println!("  store:    {} not found (run: ktalk index)", "✗".red());
    }

    // env.yaml
    let env_yaml = dir.join("env.yaml");
    if env_yaml.exists() {
        println!("  env.yaml: {} {}", "✓".green(), env_yaml.display());
    } else {
        println!("  env.yaml: {} not found (run: ktalk setup)", "✗".red());
    }

    // mod store
    let mod_dir = dir.join("mod");
    if mod_dir.exists() {
        let proposals = fs::read_dir(mod_dir.join("proposals"))
            .map(|d| d.count())
            .unwrap_or(0);
        println!("  mod store: {} ({} proposals)", "✓".green(), proposals);
    } else {
        println!("  mod store: {} (no modifications yet)", "–".dimmed());
    }

    ExitCode::SUCCESS
}

fn cmd_env() -> ExitCode {
    let path = ktalk_dir().join("env.yaml");
    match fs::read_to_string(&path) {
        Ok(content) => {
            println!("{}", "hardware environment:".cyan().bold());
            for line in content.lines() {
                println!("  {line}");
            }
            ExitCode::SUCCESS
        }
        Err(_) => {
            eprintln!(
                "{} env.yaml not found. Run {} first.",
                "error:".red().bold(),
                "ktalk setup".yellow()
            );
            ExitCode::FAILURE
        }
    }
}

// ── Main ──────────────────────────────────────────────────────────────────────

fn main() -> ExitCode {
    let cli = Cli::parse();
    let python = find_python(cli.python.as_deref());

    let mut storage_args: Vec<String> = vec![];
    if let Some(s) = &cli.storage {
        storage_args.extend(["--storage".to_string(), s.clone()]);
    }

    match cli.command {
        Commands::Version => cmd_version(),

        Commands::Status => cmd_status(),

        Commands::Env => cmd_env(),

        Commands::Completions { shell } => {
            use clap::CommandFactory;
            use clap_complete::generate;
            let mut cmd = Cli::command();
            let name = cmd.get_name().to_string();
            generate(shell, &mut cmd, name, &mut std::io::stdout());
            ExitCode::SUCCESS
        }

        Commands::Query { query, top_k, format } => {
            let q = query.join(" ");
            let mut args = vec![
                "query".to_string(),
                q,
                "--top-k".to_string(),
                top_k.to_string(),
                "--format".to_string(),
                format,
            ];
            args.extend(storage_args);
            run_python(&python, &args.iter().map(String::as_str).collect::<Vec<_>>())
        }

        Commands::Index { kernel, batch } => {
            let mut args = vec!["index".to_string()];
            if let Some(k) = kernel {
                args.extend(["--kernel".to_string(), k]);
            }
            args.extend(["--batch".to_string(), batch.to_string()]);
            args.extend(storage_args);
            run_python(&python, &args.iter().map(String::as_str).collect::<Vec<_>>())
        }

        Commands::Mod { args } => {
            let mut full = vec!["mod".to_string()];
            full.extend(args);
            run_python(&python, &full.iter().map(String::as_str).collect::<Vec<_>>())
        }

        Commands::Train { args } => {
            let mut full = vec!["train".to_string()];
            full.extend(args);
            run_python(&python, &full.iter().map(String::as_str).collect::<Vec<_>>())
        }

        Commands::Eval { args } => {
            let mut full = vec!["eval".to_string()];
            full.extend(args);
            run_python(&python, &full.iter().map(String::as_str).collect::<Vec<_>>())
        }

        Commands::Setup { yes, force } => {
            let script = project_root().join("scripts/setup.sh");
            if !script.exists() {
                eprintln!("{} scripts/setup.sh not found", "error:".red().bold());
                return ExitCode::FAILURE;
            }
            let mut cmd = Command::new("bash");
            cmd.arg(&script);
            if yes { cmd.arg("--yes"); }
            if force { cmd.arg("--force"); }
            match cmd.status() {
                Ok(s) => {
                    if s.success() { ExitCode::SUCCESS }
                    else { ExitCode::FAILURE }
                }
                Err(e) => {
                    eprintln!("{} {}", "error:".red().bold(), e);
                    ExitCode::FAILURE
                }
            }
        }
    }
}
